name: Add Reviews to Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  add_reviews:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Add Reviewers
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const pr_number = context.payload.pull_request.number;
          const reviewers = ["Eashwarsai", "AnanthulaShravya"] ; // Add your reviewers here
          for (const reviewer of reviewers) {
            await github.pulls.createReviewRequest({
              owner,
              repo,
              pull_number: pr_number,
              reviewers: [reviewer]
            });
          }