name: Add Reviews to Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  add_reviews:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Add Reviewers
      env:
        REVIEWERS: Eashwarsai  # Add your reviewers here
      run: |
        REVIEWERS_ARRAY=(${REVIEWERS//,/ })
        PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
        for reviewer in "${REVIEWERS_ARRAY[@]}"; do
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/requested_reviewers" \
            -d "{\"reviewers\": [\"$reviewer\"]}"
        done